import { jsPDF } from 'jspdf';

/**
 * Export utilities for downloading AI results in various formats
 */

/**
 * Download text content as a file
 */
export function downloadAsText(content: string, filename: string = 'kimi-cyber-result.txt') {
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Download markdown content as a file
 */
export function downloadAsMarkdown(content: string, filename: string = 'kimi-cyber-result.md') {
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Convert markdown content to formatted text for PDF
 */
function markdownToPlainText(markdown: string): string {
  // Remove markdown syntax while preserving structure
  let text = markdown;
  
  // Headers
  text = text.replace(/^#{1,6}\s+(.+)$/gm, (_, content) => content.toUpperCase() + '\n');
  
  // Bold
  text = text.replace(/\*\*(.+?)\*\*/g, '$1');
  
  // Italic
  text = text.replace(/\*(.+?)\*/g, '$1');
  
  // Code blocks
  text = text.replace(/```[\s\S]*?```/g, (match) => {
    return match.replace(/```\w*\n?/g, '').trim();
  });
  
  // Inline code
  text = text.replace(/`(.+?)`/g, '$1');
  
  // Links
  text = text.replace(/\[(.+?)\]\((.+?)\)/g, '$1 ($2)');
  
  // Lists
  text = text.replace(/^[\*\-]\s+/gm, '• ');
  text = text.replace(/^\d+\.\s+/gm, '');
  
  return text;
}

/**
 * Download content as PDF with proper formatting
 */
export function downloadAsPDF(
  content: string,
  query: string = '',
  filename: string = 'kimi-cyber-result.pdf'
) {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - (margin * 2);
  const lineHeight = 7;
  let yPosition = margin;

  // Add title
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Kimi Cyber - AI Analysis Report', margin, yPosition);
  yPosition += lineHeight * 1.5;

  // Add query if provided
  if (query) {
    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'italic');
    const queryLines = pdf.splitTextToSize(`Query: ${query}`, maxWidth);
    pdf.text(queryLines, margin, yPosition);
    yPosition += (queryLines.length * lineHeight) + lineHeight;
  }

  // Add date
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Generated: ${new Date().toLocaleString()}`, margin, yPosition);
  yPosition += lineHeight * 2;

  // Add separator line
  pdf.setDrawColor(0, 255, 136); // Neon green
  pdf.setLineWidth(0.5);
  pdf.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += lineHeight;

  // Convert markdown to plain text
  const plainText = markdownToPlainText(content);

  // Add content
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  
  const lines = plainText.split('\n');
  
  for (const line of lines) {
    // Check if we need a new page
    if (yPosition > pageHeight - margin) {
      pdf.addPage();
      yPosition = margin;
    }

    if (line.trim() === '') {
      yPosition += lineHeight * 0.5;
      continue;
    }

    // Split long lines
    const wrappedLines = pdf.splitTextToSize(line, maxWidth);
    
    for (const wrappedLine of wrappedLines) {
      if (yPosition > pageHeight - margin) {
        pdf.addPage();
        yPosition = margin;
      }
      
      pdf.text(wrappedLine, margin, yPosition);
      yPosition += lineHeight;
    }
  }

  // Add footer on last page
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(128, 128, 128);
    pdf.text(
      `Page ${i} of ${totalPages} | Generated by Kimi Cyber`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  // Save the PDF
  pdf.save(filename);
}

/**
 * Generate a filename with timestamp
 */
export function generateFilename(prefix: string = 'kimi-cyber', extension: string = 'txt'): string {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
  return `${prefix}-${timestamp}.${extension}`;
}

/**
 * Detect if content mentions generated files
 */
export function detectGeneratedFiles(content: string): string[] {
  const files: string[] = [];
  const patterns = [
    /(?:created|generated|produced|made)\s+(?:a\s+)?(.+?\.(?:pdf|docx|xlsx|csv|png|jpg|jpeg))/gi,
    /(?:PDF|Excel|CSV|Image|Document|Report|Chart)\s+(?:file|document|report)/gi,
    /\b\d+\s+pages?\b/gi
  ];

  for (const pattern of patterns) {
    const matches = content.match(pattern);
    if (matches) {
      files.push(...matches);
    }
  }

  return [...new Set(files)]; // Remove duplicates
}
